name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Kluckyyou/metrics@a0b5d4b53b6c4031a6a1d3e5a9ffe5bd7fa0cbf3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Kluckyyou
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Tokyo

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: recently-used
          plugin_languages_threshold: 0%

          plugin_lines: yes
